export const initUser = {
  id: "userid",
  fullName: "user Full Name",
  username: "userName",
  email: "email phone number username contact",
  proFileImg: "https://picsum.photos/900",
  Bio: "user Description",
  saved: {},
  Tagged: {},
  Igtv: {},
  post: 0,
  followers: 123,
  following: 12312,
};
export const initPost = [
  {
    Postid: 1,
    User: { id: "userid", username: "username" },
    PostImg: "https://picsum.photos/900",
    Date: "2020-20-20",
    likes: 20034,
    Comments: [
      { total: 25 },
      { commentid: 1, comment: "random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "super random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "ultra random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "god random comment", userid: 1, likes: 1 },
      {
        commentid: 1,
        comment: "ultra got random comment",
        userid: 1,
        likes: 1,
      },
    ],
  },
  {
    Postid: 1,
    User: { id: "userid", username: "username" },
    PostImg: "https://picsum.photos/900?random=2",
    Date: "2020-20-20",
    likes: 20034,
    Comments: [
      { total: 25 },
      { commentid: 1, comment: "random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "super random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "ultra random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "god random comment", userid: 1, likes: 1 },
      {
        commentid: 1,
        comment: "ultra got random comment",
        userid: 1,
        likes: 1,
      },
    ],
  },
  {
    Postid: 1,
    User: { id: "userid", username: "username" },
    PostImg: "https://picsum.photos/900?random=3",
    Date: "2020-20-20",
    likes: 20034,
    Comments: [
      { total: 25 },
      { commentid: 1, comment: "random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "super random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "ultra random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "god random comment", userid: 1, likes: 1 },
      {
        commentid: 1,
        comment: "ultra got random comment",
        userid: 1,
        likes: 1,
      },
    ],
  },
  {
    Postid: 1,
    User: { id: "userid", username: "username" },
    PostImg: "https://picsum.photos/900?random=4",
    Date: "2020-20-20",
    likes: 20034,
    Comments: [
      { total: 25 },
      { commentid: 1, comment: "random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "super random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "ultra random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "god random comment", userid: 1, likes: 1 },
      {
        commentid: 1,
        comment: "ultra got random comment",
        userid: 1,
        likes: 1,
      },
    ],
  },
  {
    Postid: 1,
    User: { id: "userid", username: "username" },
    PostImg: "https://picsum.photos/900?random=5",
    Date: "2020-20-20",
    likes: 20034,
    Comments: [
      { total: 25 },
      { commentid: 1, comment: "random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "super random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "ultra random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "god random comment", userid: 1, likes: 1 },
      {
        commentid: 1,
        comment: "ultra got random comment",
        userid: 1,
        likes: 1,
      },
    ],
  },
  {
    Postid: 1,
    User: { id: "userid", username: "username" },
    PostImg: "https://picsum.photos/900?random=6",
    Date: "2020-20-20",
    likes: 20034,
    Comments: [
      { total: 25 },
      { commentid: 1, comment: "random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "super random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "ultra random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "god random comment", userid: 1, likes: 1 },
      {
        commentid: 1,
        comment: "ultra got random comment",
        userid: 1,
        likes: 1,
      },
    ],
  },
  {
    Postid: 1,
    User: { id: "userid", username: "username" },
    PostImg: "https://picsum.photos/900?random=7",
    Date: "2020-20-20",
    likes: 20034,
    Comments: [
      { total: 25 },
      { commentid: 1, comment: "random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "super random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "ultra random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "god random comment", userid: 1, likes: 1 },
      {
        commentid: 1,
        comment: "ultra got random comment",
        userid: 1,
        likes: 1,
      },
    ],
  },
  {
    Postid: 1,
    User: { id: "userid", username: "username" },
    PostImg: "https://picsum.photos/900?random=8",
    Date: "2020-20-20",
    likes: 20034,
    Comments: [
      { total: 25 },
      { commentid: 1, comment: "random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "super random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "ultra random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "god random comment", userid: 1, likes: 1 },
      {
        commentid: 1,
        comment: "ultra got random comment",
        userid: 1,
        likes: 1,
      },
    ],
  },
  {
    Postid: 1,
    User: { id: "userid", username: "username" },
    PostImg: "https://picsum.photos/900?random=9",
    Date: "2020-20-20",
    likes: 20034,
    Comments: [
      { total: 25 },
      { commentid: 1, comment: "random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "super random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "ultra random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "god random comment", userid: 1, likes: 1 },
      {
        commentid: 1,
        comment: "ultra got random comment",
        userid: 1,
        likes: 1,
      },
    ],
  },
  {
    Postid: 1,
    User: { id: "userid", username: "username" },
    PostImg: "https://picsum.photos/900?random=10",
    Date: "2020-20-20",
    likes: 20034,
    Comments: [
      { total: 25 },
      { commentid: 1, comment: "random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "super random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "ultra random comment", userid: 1, likes: 1 },
      { commentid: 1, comment: "god random comment", userid: 1, likes: 1 },
      {
        commentid: 1,
        comment: "ultra got random comment",
        userid: 1,
        likes: 1,
      },
    ],
  },
];
export const initStory = [
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=3" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=31" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=34" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=29" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=21" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=54" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=5" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=3" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=11" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=12" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=1" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
  {
    User: { id: "userid", proFileImg: "https://picsum.photos/900?random=32" },
    Stories: [
      "https://picsum.photos/900?random=1",
      "https://picsum.photos/900?random=6",
      "https://picsum.photos/900?random=4",
      "https://picsum.photos/900?random=3",
      "https://picsum.photos/900?random=12",
    ],
  },
];

export const initSuggestions = [
  {
    uid: "userid",
    username: "username",
    proFileImg: "https://picsum.photos/900?random=25",
    reason: "some  how u suggest you",
  },
  {
    uid: "userid",
    username: "username",
    proFileImg: "https://picsum.photos/900?random=27",
    reason: "some  how u suggest you",
  },
  {
    uid: "userid",
    username: "username",
    proFileImg: "https://picsum.photos/900?random=28",
    reason: "some  how u suggest you",
  },
  {
    uid: "userid",
    username: "username",
    proFileImg: "https://picsum.photos/900?random=26",
    reason: "some  how u suggest you",
  },
];
export const initFollowers = {};
export const initFollowing = {};
